# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    #needs: ["prepare"]
    runs-on: ubuntu-latest
    outputs:
      AWS_ACCOUNT_ID:      ${{ steps.retrieve_secrets.outputs.AWS_ACCOUNT_ID }}
      ECR:        ${{ steps.retrieve_secrets.outputs.ECR }} 
      
    steps:      
      - name: "Checkout current repo"
        uses: actions/checkout@v2

      - name: "Retrieve Secrets Infra-CI"
        id: retrieve_secrets
        shell: bash        
        run: |
          # Get secrets
          echo "::set-output name=AWS_ACCOUNT_ID::$(cat SECRET.json | jq -r '.AWS_ACCOUNT_ID')"
          echo "::set-output name=ECR::$(cat SECRET.json | jq -r '.ECR')"
